#!/bin/bash
# Weekly review automation
# Generates summary note every Sunday evening

VAULT_PATH="/mnt/c/Users/theoh/OneDrive/Documents/Obsidian Vault"
WEEK_NUM=$(date +%U)
YEAR=$(date +%Y)
TODAY=$(date +%Y-%m-%d)
WEEK_START=$(date -d 'last monday' +%Y-%m-%d)
WEEK_END=$(date -d 'next sunday' +%Y-%m-%d)
REVIEW_NOTE="$VAULT_PATH/Daily/Weekly Review - Week $WEEK_NUM ($WEEK_START to $WEEK_END).md"

echo "📊 Generating weekly review for Week $WEEK_NUM..."

# Count Inbox items
INBOX_COUNT=$(find "$VAULT_PATH/Inbox" -name "*.md" -type f | wc -l)
RAW_IDEAS=$(find "$VAULT_PATH/Inbox/Raw Ideas" -name "*.md" -type f | wc -l)
QUICK_CAPTURES=$(find "$VAULT_PATH/Inbox/Quick Captures" -name "*.md" -type f | wc -l)

# Get Trello completed tasks (if available)
TRELLO_DONE=$(bash ~/clawd/scripts/trello-synthesis.sh 2>&1 | grep -i "done" || echo "No completed tasks found")

# QMD memory search for weekly highlights
export PATH="$HOME/.bun/bin:$PATH"
MEMORY_HIGHLIGHTS=$(qmd query "important decisions OR key insights OR lessons learned" -n 5 2>&1 | head -20 || echo "Memory search unavailable")

# Create weekly review note
cat > "$REVIEW_NOTE" << EOF
# Weekly Review - Week $WEEK_NUM ($WEEK_START to $WEEK_END)

**Review Date:** $TODAY  
**Auto-generated by Zé** 😌

---

## 📥 Inbox Processing

**Total items:** $INBOX_COUNT  
- Raw Ideas: $RAW_IDEAS
- Quick Captures: $QUICK_CAPTURES

**Action:**
- [ ] Sort Raw Ideas → Projects/Resources
- [ ] Process Quick Captures
- [ ] Handle Requests folder
- [ ] Archive processed items

---

## 📊 Active Projects Status

### Projects/Academic Research/LAI Paper
**Deadline:** March 2026  
- Status: [Update manually]
- Progress this week: 
- Blockers: 
- Next steps: 

### Projects/Academic Research/Brisa+ Paper
**Deadline:** June 2026  
- Status: [Update manually]
- Progress: 
- Next steps: 

### Projects/Automated Job Pipeline
**Deadline:** Next week  
- Status: [Update manually]
- Progress: 
- Next steps: 

### Projects/Personal Branding
- Progress: 
- Next steps: 

### Projects/Personal Website
- Progress: 
- Next steps: 

---

## ✅ Completed Tasks (Trello DONE)

$TRELLO_DONE

---

## 💡 Memory Highlights (QMD Search)

Top insights from this week:

$MEMORY_HIGHLIGHTS

---

## 📅 Next Week Priorities

1. 
2. 
3. 

---

## 🧠 Reflections

### What went well this week?


### What could improve?


### Lessons learned?


### Energy & Focus

How was your energy management? Where did creativity flow?


---

## 🎯 Goals Progress

**Areas Review:**
- [[Areas/Career Development]] - 
- [[Areas/Health & Habits]] - 
- [[Areas/Swing Trading]] - 
- [[Areas/Content Creation]] - 

---

## 🔗 Links

- Previous: [[Weekly Review - Week $(($WEEK_NUM - 1))]]
- Next: [[Weekly Review - Week $(($WEEK_NUM + 1))]]
- [[Resources/Goal Tracking]]

---

**Created:** $TODAY by Zé 😌  
**Next review:** $(date -d 'next sunday' +%Y-%m-%d)
EOF

echo "✅ Weekly review created: Daily/Weekly Review - Week $WEEK_NUM.md"
